language: swift
xcode_project: BaseCalc.xcodeproj
xcode_scheme: BaseCalc
xcode_destination: platform=iOS Simulator,OS=13.2.2,name=iPhone 8
osx_image: xcode11.4
after_success:
  bash <(curl -s https://codecov.io/bash)
